### ISSUE TITLE
I can't withdraw DFI to external wallet.

### ISSUE THREAD

**Issue by kyoungrok0517** [DeFiCh/app#151]
I'm using Windows GUI 2.3.1. I'm failing to send DFI tokens to Cake DeFI wallet. What I see is the following error screen. My wallet is fully synchronized so I can't find the cause.

![image](https://user-images.githubusercontent.com/1051900/102746659-0f933280-43a2-11eb-81c3-01763c4c800a.png)

I dumped the app logs and attach the last part.

```
[2020-12-21 16:18:54.225] [IPC-RENDERER-error] Error: Error Occurred
    at file:///js/zchunk-index.aed762c4.js:1:222672
    at file:///js/zchunk-index.aed762c4.js:1:222198
    at Object.return (file:///js/zchunk-index.aed762c4.js:1:222303)
    at p (file:///js/zchunk-2.fa83e5a5.js:21:124458)
    at Object.cancel (file:///js/zchunk-2.fa83e5a5.js:21:124241)
    at file:///js/zchunk-2.fa83e5a5.js:21:123005
    at Array.forEach (<anonymous>)
    at Object.c [as cancelAll] (file:///js/zchunk-2.fa83e5a5.js:21:122971)
    at Object.F.c.cancel (file:///js/zchunk-2.fa83e5a5.js:21:123585)
    at C (file:///js/zchunk-2.fa83e5a5.js:21:119132)
[2020-12-21 16:22:50.064] [IPC-RENDERER-error] Got error in sendToAddress: Error: Request failed with status code 500

```

**Comment by izzycsy** [comment]
Hi @kyoungrok0517 , thanks for your feedback. We're aware of this issue and are currently investigating this. In the mean time, these links may help:
<https://www.reddit.com/r/defiblockchain/comments/k92k2l/how_to_rescue_stuck_dfi/>
<https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>

**Comment by kyoungrok0517** [comment]
Thanks for the links. I'm doing Liquidity mining and more tokens are coming every minute. So I'm afraid that one-time solution will solve the problem without first removing all the liquidity shares, since more tokens will be generated. I'll wait for the permanent solution.

**Comment by izzycsy** [comment]
@kyoungrok0517 thank you for your patience.
