### ISSUE TITLE
WIN DeFI app: Got error in isBlockchainStarted: Error: Network Error

### ISSUE THREAD

**Issue by pfeiler** [DeFiCh/app#179]
After starting, syncing and using Defi app 2.1.4 (Windows 10) it suddenly stops working, needs to be killed via task manager and logs show lots of errors. After restart I have to sync the whole chain again. Did this for four times now. 
Bitdefender firewall allows all connections for the app.

Can you see in the logs what the problem is? 
```
[2020-12-27 13:44:36.804] [IPC-RENDERER-error] Error: File not selected
    at DialogManager.<anonymous> (C:\Users\djed\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\src\services\dialogmanager.js:134:35)
    at step (C:\Users\djed\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\src\services\dialogmanager.js:52:23)
    at Object.next (C:\Users\djed\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\src\services\dialogmanager.js:33:53)
    at fulfilled (C:\Users\djed\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\src\services\dialogmanager.js:24:58)
[2020-12-27 13:44:36.811] [IPC-RENDERER-error] Error: File not selected
    at DialogManager.<anonymous> (C:\Users\djed\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\src\services\dialogmanager.js:134:35)
    at step (C:\Users\djed\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\src\services\dialogmanager.js:52:23)
    at Object.next (C:\Users\djed\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\src\services\dialogmanager.js:33:53)
    at fulfilled (C:\Users\djed\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\src\services\dialogmanager.js:24:58)
[2020-12-27 13:44:38.341] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:42.353] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:42.593] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:44.371] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:46.341] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:48.341] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:50.351] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:52.382] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:54.342] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:56.340] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:44:58.370] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:00.343] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:02.340] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:04.341] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:06.341] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:08.373] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:10.341] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:12.342] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:14.341] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:16.343] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:18.341] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:20.372] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:22.342] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:24.340] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:26.341] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:28.342] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:45:29.825] [IPC-RENDERER-info] Force close defid
[2020-12-27 13:46:03.084] [IPC-MAIN-info] Checking for update
[2020-12-27 13:46:15.911] [IPC-MAIN-info] Node start initiated
[2020-12-27 13:46:15.924] [IPC-MAIN-info] Update for version 2.1.4 is not available (latest version: 2.1.4, downgrade is disallowed).
[2020-12-27 13:46:15.928] [IPC-MAIN-debug] checkForUpdatesAndNotify called, downloadPromise is null
[2020-12-27 13:46:18.127] [IPC-MAIN-info] Node started
[2020-12-27 13:46:20.174] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Request failed with status code 500
[2020-12-27 13:46:22.158] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Request failed with status code 500
[2020-12-27 13:46:24.158] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Request failed with status code 500
[2020-12-27 13:46:26.157] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Request failed with status code 503
[2020-12-27 13:46:26.508] [IPC-RENDERER-info] Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover.
[2020-12-27 13:46:30.169] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:46:30.407] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:46:32.179] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:46:32.202] [IPC-RENDERER-info] Node start initiated
[2020-12-27 13:46:34.158] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Network Error
[2020-12-27 13:46:34.258] [IPC-RENDERER-info] Node started
[2020-12-27 13:51:34.431] [IPC-RENDERER-info] {}
[2020-12-27 13:51:57.291] [IPC-MAIN-info] Checking for update
[2020-12-27 13:51:58.330] [IPC-MAIN-info] Node start initiated
[2020-12-27 13:51:59.249] [IPC-MAIN-info] Update for version 2.1.4 is not available (latest version: 2.1.4, downgrade is disallowed).
[2020-12-27 13:51:59.252] [IPC-MAIN-debug] checkForUpdatesAndNotify called, downloadPromise is null
[2020-12-27 13:52:00.485] [IPC-MAIN-info] Node started
[2020-12-27 13:52:02.511] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Request failed with status code 500
[2020-12-27 13:52:04.498] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Request failed with status code 500
[2020-12-27 13:52:06.497] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Request failed with status code 500
[2020-12-27 13:52:08.498] [IPC-RENDERER-error] Got error in isBlockchainStarted: Error: Request failed with status code 500
```

**Comment by izzycsy** [comment]
Hi @pfeiler , thanks for your feedback. Do you have any screenshots / screen recordings that displays what you're facing? Also, could you send your app logs? We need more details in order investigate how to reproduce this issue. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103274838-a04ebb80-49fd-11eb-90c8-efad4c10ca75.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103274847-a3e24280-49fd-11eb-97d4-c95e23608508.png">

<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/103274851-a5ac0600-49fd-11eb-9b00-d4ef16ea3b80.png">

**Comment by Mekiso** [comment]
Hi Izzy,

I have the same problem. It always occures when restarting the app. The start screen loads for a while  and then states the message:  "Unable to start blockchain" (similar to #106 ) after restarting everything has to be resynced like in #138.
My log files are attached. I do not get the out of memory error like in #138 but get the network error similar to the op of this issue.

Thanks
Andy

File is to big for github attachment: You can download all 3 of my loggs here: [https://we.tl/t-EdFJDRnTOY ](url)

**Comment by izzycsy** [comment]
Hi @Mekiso , thanks for your feedback. I'm unable to see anything in the link you provided for your app logs, could you **drag and drop** in the comment box to send them over? If the file size is too big, at least the app log. Please give the team time to investigate this issue, thank you for your understanding!

**Comment by AndyThoma** [comment]
Hi @izzycsy 
you need to copy - paste the link. I don't know why git doesn't forward you to the web page.
The app log and config file is attached. If you also need the binary, Please follow the link.
All the best
Andy
[app_log.zip](https://github.com/DeFiCh/app/files/5764266/app_log.zip)

**Comment by izzycsy** [comment]
Thanks for the tip @AndyThoma , well received on your app log. Please give us time to investigate this issue.

**Comment by izzycsy** [comment]
@Mekiso logs are well received. Thank you.

**Comment by izzycsy** [comment]
@pfeiler @Mekiso @AndyThoma , in the mean time, v2.1.5 is out, <https://defichain.com/downloads/>. 

 Please give a thumbs up to this comment if your issue has been resolved, if not, we'll further investigate. Thank you.

**Comment by pfeiler** [comment]
Moved my coins to Bittrex .. will try at another time
