### ISSUE TITLE
Windows | recipient() does not refer to any valid address

### ISSUE THREAD

**Issue by Darkwinde** [DeFiCh/app#416]
Hi all,

I tried to swap DFI to BTC/ETH/USDT in DEX and get the error "recipient () does not refer to any valid address"

<img src="https://user-images.githubusercontent.com/7759961/106071119-0bc3a000-6106-11eb-8a30-d7d7c2d1090b.PNG" width="75%">

Wallet: 2.1.13
Type: Windows 10 - 10.0.19042

App Log: [recipient_error.log](https://github.com/DeFiCh/ain/files/5883915/recipient_error.log)
```
[2021-01-28 00:36:38.039] [IPC-RENDERER-error] [isBlockchainStarted] {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:104168)\n    at XMLHttpRequest.f.onreadystatechange (file:///vendor.d5241135cfdddf9a65b1.js:8:97988)","config":{"url":"/","method":"post","data":"{\"jsonrpc\":\"1.0\",\"id\":\"7307471533660646\",\"method\":\"getblockchaininfo\",\"params\":[]}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","cache-control":"no-cache"},"baseURL":"http://VbdLrwkL:a190c202d4321c8ef4f108c5db0cb9f715556e7bf254c55483118644611275e3@127.0.0.1:8555","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
[2021-01-28 00:36:40.036] [IPC-RENDERER-error] [isBlockchainStarted] {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:104168)\n    at XMLHttpRequest.f.onreadystatechange (file:///vendor.d5241135cfdddf9a65b1.js:8:97988)","config":{"url":"/","method":"post","data":"{\"jsonrpc\":\"1.0\",\"id\":\"19090923680263283\",\"method\":\"getblockchaininfo\",\"params\":[]}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","cache-control":"no-cache"},"baseURL":"http://VbdLrwkL:a190c202d4321c8ef4f108c5db0cb9f715556e7bf254c55483118644611275e3@127.0.0.1:8555","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
[2021-01-28 00:36:42.036] [IPC-RENDERER-error] [isBlockchainStarted] {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:104168)\n    at XMLHttpRequest.f.onreadystatechange (file:///vendor.d5241135cfdddf9a65b1.js:8:97988)","config":{"url":"/","method":"post","data":"{\"jsonrpc\":\"1.0\",\"id\":\"6279281580117477\",\"method\":\"getblockchaininfo\",\"params\":[]}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","cache-control":"no-cache"},"baseURL":"http://VbdLrwkL:a190c202d4321c8ef4f108c5db0cb9f715556e7bf254c55483118644611275e3@127.0.0.1:8555","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
[2021-01-28 00:37:04.887] [IPC-RENDERER-info] [handleTestPoolSwapTo] "Starting"
[2021-01-28 00:37:11.277] [IPC-RENDERER-info] [handlePoolSwap] "Starting"
[2021-01-28 00:37:11.314] [IPC-RENDERER-info] [handlePoolSwap] "1. Address  Amount 0"
[2021-01-28 00:37:11.317] [IPC-RENDERER-info] [handlePoolSwap] "Account to Account"
[2021-01-28 00:37:11.319] [IPC-RENDERER-info] [handlePoolSwap] "UTXOs to Account"
[2021-01-28 00:37:11.337] [IPC-RENDERER-error]  "Request failed with status code 500"
[2021-01-28 00:37:44.411] [IPC-RENDERER-info] [handleTestPoolSwapTo] "Starting"
[2021-01-28 00:37:55.788] [IPC-RENDERER-info] [handlePoolSwap] "Starting"
[2021-01-28 00:37:55.818] [IPC-RENDERER-info] [handlePoolSwap] "1. Address  Amount 0"
[2021-01-28 00:37:55.819] [IPC-RENDERER-info] [handlePoolSwap] "Account to Account"
[2021-01-28 00:37:55.820] [IPC-RENDERER-info] [handlePoolSwap] "UTXOs to Account"
[2021-01-28 00:37:55.844] [IPC-RENDERER-error]  "Request failed with status code 500"
```

**Comment by Plutoris** [comment]
I just receive the same error message.

**Comment by Kracht** [comment]
Open console and try:

>utxostoaccount {"ADDRESS":"AMOUNT@DFI"}

e.g.

>utxostoaccount {"yFgrUd8RdL39Yrsqnv9B3yFXnaThGqQ2bm":"1.0@DFI"}

Then go back to DEX and try again.

Same Issue as https://github.com/DeFiCh/app/issues/401

**Comment by Darkwinde** [comment]
Looks the blockchain got currupted somehow. Have to reindex again :( Will try tomorrow after sync is finished

**Comment by Gilli1545** [comment]
Same error message with 2.1.13. console with utxostoaccount {"ADDRESS":"AMOUNT@DFI"} solved the problem.

**Comment by Darkwinde** [comment]
can confirm, command "utxostoaccount" solved the issue.

**Comment by izzycsy** [comment]
Hi @Darkwinde @Plutoris @Gilli1545 , the error occurs because you've `0` accountDFI balance — which is required to perform swap and other functions. The app tries to search for an address to deposit into so it looks for a DFI address but can’t find any, hence the error. As @Kracht mentioned, please try the following via `CLI`.  

Send 1 DFI to your own address:  
`utxostoaccount {“your_address”:”1.0@DFI"}` 
 eg. `utxostoaccount {“tqEwHra78cNvs4MHaHzTFPRbr7enwHyFrG”:”1.0@DFI"}` 

Check balances again: 
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

Try the function again.

**Comment by izzycsy** [comment]
Hi @Darkwinde , if the issue [`v2.1.13 Error: Corrupted block database detected`](https://github.com/DeFiCh/app/issues/390) persist, we can further discuss on the problem there. Let's keep same issues in one thread. Send screenshots of your error, activity monitor and app logs — more info in the thread. Thank you.

**Comment by Darkwinde** [comment]
Hi @izzycsy,
after using CLI command it worked. 👍 Interresting that I only have to do it once. After it I could do what ever I want with the rest of my funds 😄 

From user perspective, was a bit irritating why a DFI transfer from Bittrex to the wallet (which correctly showed the funds) is leading to the issue. Transferring the funds, I would assume that accountDFI balance is been implicitly done. 😃 

If this two steps are required / mandatory...maybe worth to think about a red text highligthing on this, if the wallet detects funds but no address balance. By a button, the user could trigger this action then without CLI command and with a confirmation dialog outlining the fees and why this is required once befor DEX swap and other services will work, would help a lot and improve user experience.

**Comment by izzycsy** [comment]
Hi @Darkwinde @Kracht @Gilli1545 @Plutoris , this issue should be fixed in the upcoming release, I'll keep you updated when it's ready. Thank you for your patience.

**Comment by izzycsy** [comment]
Hi @Darkwinde @Kracht @Gilli1545 @Plutoris , update [v2.1.17](https://defichain.com/downloads/) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
