### ISSUE TITLE
Node disconnected

### ISSUE THREAD

**Issue by jpressler** [DeFiCh/app#428]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
2.1.14
- **Previous DeFi App Version:**
2.1.13
- **Operating System (OS):**
Windows 10 Enterprise (1809)

### Screenshot(s) / screen recording(s) of issue

![grafik](https://user-images.githubusercontent.com/8121817/106300783-2eb19980-6257-11eb-92f7-5f04bc143033.png)

### Expected Behavior

sync to 100% of blockchain expected. Or even before no need to sync the whole blockchain was expected.

### App log / binary log / app config

[app_logs.zip](https://github.com/DeFiCh/app/files/5894974/app_logs.zip)

**Comment by jpressler** [comment]
Once again after restart and approx. 1:45h of sync at 99.60% ...

[2021-01-29 17:42:51.779] [IPC-MAIN-info] [Starting Electron App] OS Windows 10 - 10.0.17763
[2021-01-29 17:42:51.804] [IPC-MAIN-info] Checking for update
[2021-01-29 17:42:53.602] [IPC-RENDERER-info]  "[Starting App] App is running with version 2.1.14"
[2021-01-29 17:43:04.100] [IPC-RENDERER-info] Node start initiated
[2021-01-29 17:43:04.720] [IPC-RENDERER-info] Update for version 2.1.14 is not available (latest version: 2.1.14, downgrade is disallowed).
[2021-01-29 17:43:04.723] [IPC-RENDERER-debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-01-29 17:43:07.519] [IPC-RENDERER-info] Node started
[2021-01-29 17:43:09.569] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-01-29 17:43:11.549] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-01-29 17:43:13.550] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-01-29 17:43:15.549] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-01-29 17:43:17.549] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-01-29 17:43:19.549] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-01-29 17:43:21.719] [IPC-RENDERER-info] [Blockchain Status] "blockchain started successfully"
[2021-01-29 19:28:27.039] [IPC-RENDERER-error] [startBinary] "terminate called without an active exception"
[2021-01-29 19:28:27.077] [IPC-RENDERER-info] [Blockchain Status] "terminate called without an active exception"
[2021-01-29 19:28:27.085] [IPC-RENDERER-error] [blockChainNotStarted - Running] "Node is disconnected"
[2021-01-29 19:28:27.312] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:27.321] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:27.981] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:27.988] [IPC-RENDERER-error] [queueWorker] "{\"message\":\"Network Error\",\"name\":\"Error\",\"stack\":\"Error: Network Error\\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\\n    at XMLHttpRequest.f.onerror (file:///vendor.d5241135cfdddf9a65b1.js:8:98106)\",\"config\":{\"url\":\"/\",\"method\":\"post\",\"data\":\"{\\\"jsonrpc\\\":\\\"1.0\\\",\\\"id\\\":\\\"5075659847465954\\\",\\\"method\\\":\\\"getbalance\\\",\\\"params\\\":[\\\"*\\\"]}\",\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json;charset=utf-8\",\"cache-control\":\"no-cache\"},\"baseURL\":\"http://MyWfRxoT:88d7decdf8a7929987ea0156cd586f4889965bb92c112b20acdc115385990aee@127.0.0.1:8555\",\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1}}"
[2021-01-29 19:28:28.026] [IPC-RENDERER-error]  "Network Error"
[2021-01-29 19:28:28.032] [IPC-RENDERER-error] [function(){return ur(void 0,void 0,void 0,(function(){var e,t;return dr(this,(function(n){switch(n.label){case 0:return[4,kr()];case 1:return e=n.sent(),[4,wr()];case 2:return t=n.sent(),[2,new(Me())(e).plus(t).toFixed(8)]}}))}))}] "{\"message\":\"Network Error\",\"name\":\"Error\",\"stack\":\"Error: Network Error\\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\\n    at XMLHttpRequest.f.onerror (file:///vendor.d5241135cfdddf9a65b1.js:8:98106)\",\"config\":{\"url\":\"/\",\"method\":\"post\",\"data\":\"{\\\"jsonrpc\\\":\\\"1.0\\\",\\\"id\\\":\\\"5075659847465954\\\",\\\"method\\\":\\\"getbalance\\\",\\\"params\\\":[\\\"*\\\"]}\",\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json;charset=utf-8\",\"cache-control\":\"no-cache\"},\"baseURL\":\"http://MyWfRxoT:88d7decdf8a7929987ea0156cd586f4889965bb92c112b20acdc115385990aee@127.0.0.1:8555\",\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1}}"
[2021-01-29 19:28:28.043] [IPC-RENDERER-error] [queueWorker] "{\"message\":\"Network Error\",\"name\":\"Error\",\"stack\":\"Error: Network Error\\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\\n    at XMLHttpRequest.f.onerror (file:///vendor.d5241135cfdddf9a65b1.js:8:98106)\",\"config\":{\"url\":\"/\",\"method\":\"post\",\"data\":\"{\\\"jsonrpc\\\":\\\"1.0\\\",\\\"id\\\":\\\"9594448660217887\\\",\\\"method\\\":\\\"getbalances\\\",\\\"params\\\":[]}\",\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json;charset=utf-8\",\"cache-control\":\"no-cache\"},\"baseURL\":\"http://MyWfRxoT:88d7decdf8a7929987ea0156cd586f4889965bb92c112b20acdc115385990aee@127.0.0.1:8555\",\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1}}"
[2021-01-29 19:28:28.049] [IPC-RENDERER-error]  "Network Error"
[2021-01-29 19:28:28.054] [IPC-RENDERER-error] [function(){return ur(void 0,void 0,Promise,(function(){return dr(this,(function(e){switch(e.label){case 0:return[4,(new ci).getPendingBalance()];case 1:return[2,e.sent()]}}))}))}] "{\"message\":\"Network Error\",\"name\":\"Error\",\"stack\":\"Error: Network Error\\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\\n    at XMLHttpRequest.f.onerror (file:///vendor.d5241135cfdddf9a65b1.js:8:98106)\",\"config\":{\"url\":\"/\",\"method\":\"post\",\"data\":\"{\\\"jsonrpc\\\":\\\"1.0\\\",\\\"id\\\":\\\"9594448660217887\\\",\\\"method\\\":\\\"getbalances\\\",\\\"params\\\":[]}\",\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json;charset=utf-8\",\"cache-control\":\"no-cache\"},\"baseURL\":\"http://MyWfRxoT:88d7decdf8a7929987ea0156cd586f4889965bb92c112b20acdc115385990aee@127.0.0.1:8555\",\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1}}"
[2021-01-29 19:28:28.062] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:28.249] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:28.986] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:28.998] [IPC-RENDERER-error] [queueWorker] "{\"message\":\"Network Error\",\"name\":\"Error\",\"stack\":\"Error: Network Error\\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\\n    at XMLHttpRequest.f.onerror (file:///vendor.d5241135cfdddf9a65b1.js:8:98106)\",\"config\":{\"url\":\"/\",\"method\":\"post\",\"data\":\"{\\\"jsonrpc\\\":\\\"1.0\\\",\\\"id\\\":\\\"11220466412750874\\\",\\\"method\\\":\\\"getbalance\\\",\\\"params\\\":[\\\"*\\\"]}\",\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json;charset=utf-8\",\"cache-control\":\"no-cache\"},\"baseURL\":\"http://MyWfRxoT:88d7decdf8a7929987ea0156cd586f4889965bb92c112b20acdc115385990aee@127.0.0.1:8555\",\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1}}"
[2021-01-29 19:28:29.004] [IPC-RENDERER-error]  "Network Error"
[2021-01-29 19:28:29.010] [IPC-RENDERER-error] [function(){return ur(void 0,void 0,void 0,(function(){var e,t;return dr(this,(function(n){switch(n.label){case 0:return[4,kr()];case 1:return e=n.sent(),[4,wr()];case 2:return t=n.sent(),[2,new(Me())(e).plus(t).toFixed(8)]}}))}))}] "{\"message\":\"Network Error\",\"name\":\"Error\",\"stack\":\"Error: Network Error\\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\\n    at XMLHttpRequest.f.onerror (file:///vendor.d5241135cfdddf9a65b1.js:8:98106)\",\"config\":{\"url\":\"/\",\"method\":\"post\",\"data\":\"{\\\"jsonrpc\\\":\\\"1.0\\\",\\\"id\\\":\\\"11220466412750874\\\",\\\"method\\\":\\\"getbalance\\\",\\\"params\\\":[\\\"*\\\"]}\",\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json;charset=utf-8\",\"cache-control\":\"no-cache\"},\"baseURL\":\"http://MyWfRxoT:88d7decdf8a7929987ea0156cd586f4889965bb92c112b20acdc115385990aee@127.0.0.1:8555\",\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1}}"
[2021-01-29 19:28:29.017] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:29.156] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:29.179] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:29.633] [IPC-RENDERER-info] DefiProcessManager close with code 3
[2021-01-29 19:28:29.636] [IPC-RENDERER-info] Error occurred while running binary with code: 3
[2021-01-29 19:28:29.641] [IPC-RENDERER-error] [startBinary] {"success":false}
[2021-01-29 19:28:29.646] [IPC-RENDERER-info] [Blockchain Status] {"success":false}
[2021-01-29 19:28:29.651] [IPC-RENDERER-error] [blockChainNotStarted - Running] "Node is disconnected"
[2021-01-29 19:28:30.002] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:30.006] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:30.158] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:30.282] [IPC-RENDERER-error]  "Network Error"
[2021-01-29 19:28:30.396] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:30.992] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-01-29 19:28:31.153] [IPC-RENDERER-error] [queueWorker] "{\"message\":\"Network Error\",\"name\":\"Error\",\"stack\":\"Error: Network Error\\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\\n    at XMLHttpRequest.f.onerror (file:///vendor.d5241135cfdddf9a65b1.js:8:98106)\",\"config\":{\"url\":\"/\",\"method\":\"post\",\"data\":\"{\\\"jsonrpc\\\":\\\"1.0\\\",\\\"id\\\":\\\"6106699405305576\\\",\\\"method\\\":\\\"getbalances\\\",\\\"params\\\":[]}\",\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json;charset=utf-8\",\"cache-control\":\"no-cache\"},\"baseURL\":\"http://MyWfRxoT:88d7decdf8a7929987ea0156cd586f4889965bb92c112b20acdc115385990aee@127.0.0.1:8555\",\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1}}"
[2021-01-29 19:28:31.157] [IPC-RENDERER-error]  "Network Error"

**Comment by MrWild1412** [comment]
Same issue here. resynced 3 times and always stopped at around 99,X % (last time 604335)

**Comment by jpressler** [comment]
now this repeated for two times after stopping and restarting the app ... Node connectin lost at almost 99.60% ... no access to the wallet for a day now. Also the sync of the blockchain extremly slows down at almost 85% sync ... any comments?

**Comment by stevenschubert** [comment]
I've got the same issue and also resynced it and always receive the same connection error.

**Comment by kingsersch** [comment]
Picture is from today. Unable to start blockchain
![bandicam 2021-01-30 13-24-17-038](https://user-images.githubusercontent.com/77615565/106356281-d209b980-62fe-11eb-9f1c-98c11b796964.jpg)

**Comment by Ausafari** [comment]
I'm having the exact same problem. Get to 99.73% synchronisation every time and then (the English version of) the same "Node disconnected" error. No access to the app for over 24 hours. This is once again the sort of poor performance that stops wider adoption of both the app and the project.

**Comment by MrWild1412** [comment]
> Same issue here. resynced 3 times and always stopped at around 99,X % (last time 604335)

it's working again :) 
1. deleted the folder in C:\Users\XXX\AppData\Roaming\DeFi Blockchain   -> not the defi-app folder
2. installed 2.1.15
3. waited for the succesful sync 
4. closed the app (my balances weren't right)
5. opened the app again and voila =)

**Comment by izzycsy** [comment]
Hi @jpressler @stevenschubert @Ausafari , thanks for your feedback, could you try updating to the latest [v2.1.15](https://defichain.com/downloads/)? If error persist, kindly send your logs again. Thank you. 

Hi @MrWild1412 appreciate the help!
