### ISSUE TITLE
Windows: IPC-RENDERER-error : Network Error 500

### ISSUE THREAD

**Issue by MarcBenTobit** [DeFiCh/app#475]
- Version: 2.1.15
Platform: Windows 10 Home ( 10.0.19041 )

### Actual Behavior
Sync do not start at all

### Expected Behavior
Sync should be starting

### App log / binary log / app config
[2021-02-06 12:56:20.369] [IPC-RENDERER-info] Node start initiated
[2021-02-06 12:56:21.819] [IPC-RENDERER-info] Node started
[2021-02-06 12:56:23.873] [IPC-RENDERER-info] [Blockchain Status] "blockchain started successfully"
[2021-02-06 13:03:34.577] [IPC-RENDERER-error] [getBlockSyncInfo] "Request failed with status code 500"
[2021-02-06 15:49:28.705] [IPC-RENDERER-error] [fetchBlockSyncInfo] "Network Error"
[2021-02-06 15:50:08.541] [IPC-RENDERER-error] Error: File not selected
    at DialogManager.<anonymous> (C:\Users\[username]\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\electron-app\src\services\dialogmanager.js:134:35)
    at step (C:\Users\[username]\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\electron-app\src\services\dialogmanager.js:52:23)
    at Object.next (C:\Users\[username]\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\electron-app\src\services\dialogmanager.js:33:53)
    at fulfilled (C:\Users\[username]\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\electron-app\src\services\dialogmanager.js:24:58)
[2021-02-06 15:50:08.542] [IPC-RENDERER-error] Error: File not selected
    at DialogManager.<anonymous> (C:\Users\[username]\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\electron-app\src\services\dialogmanager.js:134:35)
    at step (C:\Users\[username]\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\electron-app\src\services\dialogmanager.js:52:23)
    at Object.next (C:\Users\[username]\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\electron-app\src\services\dialogmanager.js:33:53)
    at fulfilled (C:\Users\[username]\AppData\Local\Programs\defi-app\resources\app.asar\electron-app\build\electron-app\src\services\dialogmanager.js:24:58)

total new laptop.

C:\Users\[username]>ping localhost

Ping wird ausgeführt für LAPTOP-C3JOECB8 [::1] mit 32 Bytes Daten:
Antwort von ::1: Zeit<1ms
Antwort von ::1: Zeit<1ms
Antwort von ::1: Zeit<1ms
Antwort von ::1: Zeit<1ms

Ping-Statistik für ::1:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 0ms, Maximum = 0ms, Mittelwert = 0ms

C:\Users\[username]>ping 127.0.0.1

Ping wird ausgeführt für 127.0.0.1 mit 32 Bytes Daten:
Antwort von 127.0.0.1: Bytes=32 Zeit<1ms TTL=128
Antwort von 127.0.0.1: Bytes=32 Zeit<1ms TTL=128
Antwort von 127.0.0.1: Bytes=32 Zeit<1ms TTL=128
Antwort von 127.0.0.1: Bytes=32 Zeit<1ms TTL=128

Ping-Statistik für 127.0.0.1:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 0ms, Maximum = 0ms, Mittelwert = 0ms

SOLUTION:

Hi @inyo, Hi @Babwenbiber,
looks some nodes currently have issues. You can add a synced one by console command. You can use my, if you like:

addnode "62.75.139.29:8555" add

**Comment by Babwenbiber** [comment]
Thank you,
working for me
