### ISSUE TITLE
MacOS Catalina App doesn't startup

### ISSUE THREAD

**Issue by delueg** [DeFiCh/app#635]
Please see following: my app logfile
`[2021-03-11 11:41:52.019] [IPC-MAIN-info]  [Starting Electron App] OS macOS Catalina - 19.6.0
[2021-03-11 11:41:52.069] [IPC-MAIN-info]  Checking for update
[2021-03-11 11:41:52.072] [IPC-MAIN-error] Error: ENOENT: no such file or directory, open '/Users/myuser/Library/Application Support/Defi/wallets/wallet_map.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.writeFileSync (fs.js:1366:35)
    at Object.createWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:382:29)
    at Object.initializeWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:393:17)
    at App.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:102:35)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:33:53)
    at fulfilled (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-03-11 11:41:53.719] [IPC-MAIN-info]  Generated new staging user ID: 4efabd9b-05b5-5eef-a836-066f5d6e0931
[2021-03-11 11:41:54.540] [IPC-MAIN-info]  Update for version 2.3.1 is not available (latest version: 2.3.1, downgrade is disallowed).
[2021-03-11 11:41:54.542] [IPC-MAIN-debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-03-11 11:41:55.844] [IPC-RENDERER-error]  "Error in selected unit, setting it to default one"
[2021-03-11 11:41:57.345] [IPC-RENDERER-info]   "[Starting App] App is running with version 2.3.1"
[2021-03-11 11:41:57.367] [IPC-RENDERER-info]  [start] - Starting node connection...
[2021-03-11 11:41:57.370] [IPC-RENDERER-error] Error: ENOENT: no such file or directory, open '/Users/myuser/Library/Application Support/Defi/wallets/wallet_map.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.writeFileSync (fs.js:1366:35)
    at Object.createWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:382:29)
    at Object.createOrGetWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:93:19)
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:121:49)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
[2021-03-11 11:41:57.372] [IPC-RENDERER-error] TypeError: Cannot set property 'nodeVersion' of undefined
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:158:53)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:23:12)
    at Function.DefiProcessManager.start (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:110:16)
    at Object.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:50:78)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:33:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:14:53)
[2021-03-11 11:41:57.435] [IPC-RENDERER-error] [startBinary] "Cannot set property 'nodeVersion' of undefined"
[2021-03-11 11:41:57.441] [IPC-RENDERER-info]  [Blockchain Status] {"success":false,"data":{}}
[2021-03-11 11:41:57.445] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] ""
[2021-03-11 12:53:20.030] [IPC-RENDERER-info]  [SHUT DOWN] Starting shut down process
[2021-03-11 12:53:20.058] [IPC-RENDERER-info]  [SHUT DOWN] "Removing all Binary and Queue listeners.."
[2021-03-11 12:53:20.073] [IPC-RENDERER-info]  [SHUT DOWN] Terminating Node Connection
[2021-03-11 12:53:20.074] [IPC-RENDERER-info]  [Stop Node] Start DeFiProcessManager shutdown...
[2021-03-11 12:53:20.074] [IPC-RENDERER-error] Error: ENOENT: no such file or directory, open '/Users/myuser/.defi/defi.pid'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at Object.getFileData (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/utils.js:94:23)
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:277:39)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
[2021-03-11 12:53:20.076] [IPC-RENDERER-info]  [SHUT DOWN] Node connection has been closed
[2021-03-11 12:53:20.076] [IPC-RENDERER-info]  [SHUT DOWN] Closing app...
[2021-03-11 12:53:24.752] [IPC-MAIN-info]  [Starting Electron App] OS macOS Catalina - 19.6.0
[2021-03-11 12:53:24.758] [IPC-MAIN-info]  Checking for update
[2021-03-11 12:53:24.760] [IPC-MAIN-error] Error: ENOENT: no such file or directory, open '/Users/myuser/Library/Application Support/Defi/wallets/wallet_map.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.writeFileSync (fs.js:1366:35)
    at Object.createWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:382:29)
    at Object.initializeWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:393:17)
    at App.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:102:35)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:33:53)
    at fulfilled (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-03-11 12:53:25.518] [IPC-RENDERER-info]   "[Starting App] App is running with version 2.3.1"
[2021-03-11 12:53:25.527] [IPC-RENDERER-info]  [start] - Starting node connection...
[2021-03-11 12:53:25.529] [IPC-RENDERER-error] Error: ENOENT: no such file or directory, open '/Users/myuser/Library/Application Support/Defi/wallets/wallet_map.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.writeFileSync (fs.js:1366:35)
    at Object.createWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:382:29)
    at Object.createOrGetWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:93:19)
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:121:49)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
[2021-03-11 12:53:25.530] [IPC-RENDERER-error] TypeError: Cannot set property 'nodeVersion' of undefined
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:158:53)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:23:12)
    at Function.DefiProcessManager.start (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:110:16)
    at Object.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:50:78)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:33:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:14:53)
[2021-03-11 12:53:25.560] [IPC-RENDERER-error] [startBinary] "Cannot set property 'nodeVersion' of undefined"
[2021-03-11 12:53:25.563] [IPC-RENDERER-info]  [Blockchain Status] {"success":false,"data":{}}
[2021-03-11 12:53:25.565] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] ""
[2021-03-11 12:53:25.607] [IPC-RENDERER-info]  Update for version 2.3.1 is not available (latest version: 2.3.1, downgrade is disallowed).
[2021-03-11 12:53:25.608] [IPC-RENDERER-debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-03-11 13:00:54.033] [IPC-RENDERER-info]  [SHUT DOWN] Starting shut down process
[2021-03-11 13:00:54.059] [IPC-RENDERER-info]  [SHUT DOWN] "Removing all Binary and Queue listeners.."
[2021-03-11 13:00:54.074] [IPC-RENDERER-info]  [SHUT DOWN] Terminating Node Connection
[2021-03-11 13:00:54.075] [IPC-RENDERER-info]  [Stop Node] Start DeFiProcessManager shutdown...
[2021-03-11 13:00:54.076] [IPC-RENDERER-error] Error: ENOENT: no such file or directory, open '/Users/myuser/.defi/defi.pid'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at Object.getFileData (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/utils.js:94:23)
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:277:39)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
[2021-03-11 13:00:54.077] [IPC-RENDERER-info]  [SHUT DOWN] Node connection has been closed
[2021-03-11 13:00:54.077] [IPC-RENDERER-info]  [SHUT DOWN] Closing app...
[2021-03-11 13:00:58.630] [IPC-MAIN-info]  [Starting Electron App] OS macOS Catalina - 19.6.0
[2021-03-11 13:00:58.637] [IPC-MAIN-info]  Checking for update
[2021-03-11 13:00:58.639] [IPC-MAIN-error] Error: ENOENT: no such file or directory, open '/Users/myuser/Library/Application Support/Defi/wallets/wallet_map.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.writeFileSync (fs.js:1366:35)
    at Object.createWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:382:29)
    at Object.initializeWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:393:17)
    at App.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:102:35)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:33:53)
    at fulfilled (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-03-11 13:00:59.060] [IPC-MAIN-info]  Update for version 2.3.1 is not available (latest version: 2.3.1, downgrade is disallowed).
[2021-03-11 13:00:59.061] [IPC-MAIN-debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-03-11 13:00:59.371] [IPC-RENDERER-info]   "[Starting App] App is running with version 2.3.1"
[2021-03-11 13:00:59.381] [IPC-RENDERER-info]  [start] - Starting node connection...
[2021-03-11 13:00:59.382] [IPC-RENDERER-error] Error: ENOENT: no such file or directory, open '/Users/myuser/Library/Application Support/Defi/wallets/wallet_map.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.writeFileSync (fs.js:1366:35)
    at Object.createWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:382:29)
    at Object.createOrGetWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:93:19)
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:121:49)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
[2021-03-11 13:00:59.383] [IPC-RENDERER-error] TypeError: Cannot set property 'nodeVersion' of undefined
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:158:53)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:23:12)
    at Function.DefiProcessManager.start (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:110:16)
    at Object.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:50:78)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:33:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:14:53)
[2021-03-11 13:00:59.414] [IPC-RENDERER-error] [startBinary] "Cannot set property 'nodeVersion' of undefined"
[2021-03-11 13:00:59.417] [IPC-RENDERER-info]  [Blockchain Status] {"success":false,"data":{}}
[2021-03-11 13:00:59.419] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] ""
[2021-03-11 13:05:41.022] [IPC-RENDERER-info]  [SHUT DOWN] Starting shut down process
[2021-03-11 13:05:41.051] [IPC-RENDERER-info]  [SHUT DOWN] "Removing all Binary and Queue listeners.."
[2021-03-11 13:05:41.069] [IPC-RENDERER-info]  [SHUT DOWN] Terminating Node Connection
[2021-03-11 13:05:41.070] [IPC-RENDERER-info]  [Stop Node] Start DeFiProcessManager shutdown...
[2021-03-11 13:05:41.071] [IPC-RENDERER-error] Error: ENOENT: no such file or directory, open '/Users/myuser/.defi/defi.pid'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at Object.getFileData (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/utils.js:94:23)
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:277:39)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
[2021-03-11 13:05:41.072] [IPC-RENDERER-info]  [SHUT DOWN] Node connection has been closed
[2021-03-11 13:05:41.072] [IPC-RENDERER-info]  [SHUT DOWN] Closing app...
[2021-03-11 13:07:03.045] [IPC-MAIN-info]  [Starting Electron App] OS macOS Catalina - 19.6.0
[2021-03-11 13:07:03.057] [IPC-MAIN-info]  Checking for update
[2021-03-11 13:07:03.059] [IPC-MAIN-error] Error: ENOENT: no such file or directory, open '/Users/myuser/Library/Application Support/Defi/wallets/wallet_map.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.writeFileSync (fs.js:1366:35)
    at Object.createWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:382:29)
    at Object.initializeWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:393:17)
    at App.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:102:35)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:33:53)
    at fulfilled (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-03-11 13:07:04.112] [IPC-RENDERER-info]   "[Starting App] App is running with version 2.3.1"
[2021-03-11 13:07:04.123] [IPC-RENDERER-info]  [start] - Starting node connection...
[2021-03-11 13:07:04.125] [IPC-RENDERER-error] Error: ENOENT: no such file or directory, open '/Users/myuser/Library/Application Support/Defi/wallets/wallet_map.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.writeFileSync (fs.js:1366:35)
    at Object.createWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:382:29)
    at Object.createOrGetWalletMap (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/controllers/wallets.js:93:19)
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:121:49)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
[2021-03-11 13:07:04.127] [IPC-RENDERER-error] TypeError: Cannot set property 'nodeVersion' of undefined
    at Function.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:158:53)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:52:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:33:53)
    at /Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:23:12)
    at Function.DefiProcessManager.start (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/defiprocessmanager.js:110:16)
    at Object.<anonymous> (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:50:78)
    at step (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:33:23)
    at Object.next (/Applications/defi-app.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/ipc-events/defiprocessmanager.js:14:53)
[2021-03-11 13:07:04.140] [IPC-RENDERER-info]  Update for version 2.3.1 is not available (latest version: 2.3.1, downgrade is disallowed).
[2021-03-11 13:07:04.140] [IPC-RENDERER-debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-03-11 13:07:04.173] [IPC-RENDERER-error] [startBinary] "Cannot set property 'nodeVersion' of undefined"
[2021-03-11 13:07:04.175] [IPC-RENDERER-info]  [Blockchain Status] {"success":false,"data":{}}
[2021-03-11 13:07:04.179] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] ""
`

**Comment by RobinTorque** [comment]
There is a problem with version 2.3.1

If the app is not installed as an update, but the first time on a new system, then the blockchain folder is not created and the app cannot start. 

The problem and the fix is documented here.
https://defichain-wiki.com/wiki/V2.3.1#Known_bugs_with_this_version
