### ISSUE TITLE
MacOS Big Sur: Unable to open app after installation

### ISSUE THREAD

**Issue by Morhpois01** [DeFiCh/app#765]
#### How to reproduce it (as minimally and precisely as possible):
just open the app

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): 11.2.3
<img width="1440" alt="Bildschirmfoto 2021-04-15 um 21 50 35" src="https://user-images.githubusercontent.com/82651261/115012662-6623ff80-9eb0-11eb-8bad-abd29d514c6a.png">

**Comment by adrian-schnell** [comment]
I'm having the same issue, after opening the wallet app "nothing" happens.
the process manager shows, that these processes are started:
- Defi Wallet
- Defi Wallet Helper (GPU)
- Defi Wallet Helper

the only possible option is to open the "about" menu point like shown in the original post.


defi-cli (v1.6.3) is starting normally and syncing all blocks as expected.

**Comment by adrian-schnell** [comment]
maybe I found something - I started the app with the console and found an unhandled exception:

> /Applications/DeFi\ Wallet.app/Contents/MacOS/DeFi\ Wallet
13:31:10.725 › Error: Inconsistent data in default config
    at UiConfig.getExistingConfig (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:165:15)
    at UiConfig.<anonymous> (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:127:51)
    at step (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:63:23)
    at Object.next (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:44:53)
    at /Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:34:12)
    at UiConfig.get (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:117:16)
    at App.<anonymous> (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:245:55)
    at step (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:52:23)
Error: Inconsistent data in default config
    at UiConfig.getExistingConfig (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:165:15)
    at UiConfig.<anonymous> (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:127:51)
    at step (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:63:23)
    at Object.next (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:44:53)
    at /Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:34:12)
    at UiConfig.get (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:117:16)
    at App.<anonymous> (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:245:55)
    at step (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:52:23)
(node:42814) UnhandledPromiseRejectionWarning: Error: Inconsistent data in default config
    at UiConfig.getExistingConfig (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:165:15)
    at UiConfig.<anonymous> (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:127:51)
    at step (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:63:23)
    at Object.next (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:44:53)
    at /Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:34:12)
    at UiConfig.get (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/services/uiconfig.js:117:16)
    at App.<anonymous> (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:245:55)
    at step (/Applications/DeFi Wallet.app/Contents/Resources/app.asar/electron-app/build/electron-app/src/app.js:52:23)
(node:42814) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)


Downgrade (to app 2.3.2) or upgrade again to 2.3.3 does not solve this issue.

**Comment by CryptoFabi** [comment]
I have the exact same issue here! :-(

**Comment by izzycsy** [comment]
Hi @Morhpois01 @adrian-schnell @CryptoFabi , thanks for the feedback, please give us time to investigate. In the mean time, please keep your `wallet.dat` safe if you've funds on it.

**Comment by adrian-schnell** [comment]
fortunately, I've a couple of actual backups of my wallet.dat - and it's running on a 2nd mac (same version) without problems.

**Comment by adrian-schnell** [comment]
I found a solution:

the problem is solved after deleting the folder `/Users/%username%/.defi` and restarting the wallet

**Comment by izzycsy** [comment]
Hi @adrian-schnell , you might be right, this may have happened because the new Mac protects you from other directory. We'll get this fix in the next release. 

@CryptoFabi , can you try removing this file please? 
`/Users/<username>/.defi`

**Comment by Morhpois01** [comment]
Can someone tell me how to find the file? Under the directory of my
username, there isn't anything from DeFi Wallet.

Bella ***@***.***> schrieb am Mo., 19. Apr. 2021, 10:17:

**Comment by izzycsy** [comment]
Hi @Morhpois01 , 

1. Go to Folder 

<img width="459" alt="Mac - Go To Folder" src="https://user-images.githubusercontent.com/65014479/115211530-3b48de00-a132-11eb-99e0-a94a06886bdc.png">

2. Type: `/Users/<username>/.defi ` , it would bring you to that folder.

<img width="614" alt="_defi folder" src="https://user-images.githubusercontent.com/65014479/115211649-59164300-a132-11eb-9107-2f576d45bc11.png">

**Comment by Morhpois01** [comment]
Hi bella,

I did and it brings me to my "user" folder where I got two folders "shared"
and "<username>". And after seeing your screenshot, I tried to search for
"defi.conf", but my mac could not even find this specific file. 😬


Bella ***@***.***> schrieb am Mo., 19. Apr. 2021, 11:12:

**Comment by izzycsy** [comment]
Hi @Morhpois01 , it's a hidden folder, can you take a screenshot so I can understand how you're unable to find the folder? 
Shortcut for taking a screenshot: `command` + `shift` + `4`

**Comment by Morhpois01** [comment]
Hi Bella,

See below what I typed and what will appear..

**Comment by Morhpois01** [comment]
I just found the short key to Show my hidden files..  found it and deleted
it..  it is working now.. 💪

Bella ***@***.***> schrieb am Mo., 19. Apr. 2021, 11:37:

**Comment by izzycsy** [comment]
Hi @Morhpois01 @adrian-schnell @CryptoFabi , [v2.3.4](https://github.com/DeFiCh/app/releases/tag/v2.3.4) is out. Please read through the release notes before updating.  Do give a thumbs up to this comment if your issue has been resolved.
